# Generated by Django 5.0.3 on 2024-06-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Headline', models.CharField(max_length=100)),
                ('aboutYou', models.TextField()),
                ('eduTitle1', models.CharField(max_length=100)),
                ('eduInstitute1', models.CharField(max_length=100)),
                ('edu1Marks1', models.CharField(blank=True, max_length=100, null=True)),
                ('eduStartDate1', models.DateField(blank=True, null=True)),
                ('eduEndDate1', models.DateField(blank=True, null=True)),
                ('eduTitle2', models.CharField(blank=True, max_length=100, null=True)),
                ('eduInstitute2', models.CharField(blank=True, max_length=100, null=True)),
                ('edu1Marks2', models.CharField(blank=True, max_length=100, null=True)),
                ('eduStartDate2', models.DateField(blank=True, null=True)),
                ('eduEndDate2', models.DateField(blank=True, null=True)),
                ('eduTitle3', models.CharField(blank=True, max_length=100, null=True)),
                ('eduInstitute3', models.CharField(blank=True, max_length=100, null=True)),
                ('edu1Marks3', models.CharField(blank=True, max_length=100, null=True)),
                ('eduStartDate3', models.DateField(blank=True, null=True)),
                ('eduEndDate3', models.DateField(blank=True, null=True)),
                ('skil1', models.CharField(blank=True, max_length=100, null=True)),
                ('skil2', models.CharField(blank=True, max_length=100, null=True)),
                ('skil3', models.CharField(blank=True, max_length=100, null=True)),
                ('skil4', models.CharField(blank=True, max_length=100, null=True)),
                ('skil5', models.CharField(blank=True, max_length=100, null=True)),
                ('skil6', models.CharField(blank=True, max_length=100, null=True)),
                ('projectTitle1', models.CharField(blank=True, max_length=100, null=True)),
                ('projectDescription1', models.TextField(blank=True, null=True)),
                ('proStartDate1', models.DateField(blank=True, null=True)),
                ('proEndDate1', models.DateField(blank=True, null=True)),
                ('projectTitle2', models.CharField(blank=True, max_length=100, null=True)),
                ('projectDescription2', models.TextField(blank=True, null=True)),
                ('proStartDate2', models.DateField(blank=True, null=True)),
                ('proEndDate2', models.DateField(blank=True, null=True)),
                ('projectTitle3', models.CharField(blank=True, max_length=100, null=True)),
                ('projectDescription3', models.TextField(blank=True, null=True)),
                ('proStartDate3', models.DateField(blank=True, null=True)),
                ('proEndDate3', models.DateField(blank=True, null=True)),
                ('experienceLevel', models.CharField(choices=[('one', 'ONE'), ('two', 'TWO'), ('three', 'THREE'), ('four', 'FOUR'), ('five', 'FIVE'), ('six', 'SIX'), ('seven', 'SEVEN'), ('eight', 'EIGHT'), ('nine', 'NINE'), ('ten', 'TEN'), ('internship', 'Internship'), ('fresh', 'Fresh')], max_length=100)),
                ('experienceTitle1', models.CharField(blank=True, max_length=100, null=True)),
                ('experienceCompany1', models.CharField(blank=True, max_length=100, null=True)),
                ('expStartDate1', models.DateField(blank=True, null=True)),
                ('expEndDate1', models.DateField(blank=True, null=True)),
                ('experienceTitle2', models.CharField(blank=True, max_length=100, null=True)),
                ('experienceCompany2', models.CharField(blank=True, max_length=100, null=True)),
                ('expStartDate2', models.DateField(blank=True, null=True)),
                ('experienceTitle3', models.CharField(blank=True, max_length=100, null=True)),
                ('experienceCompany3', models.CharField(blank=True, max_length=100, null=True)),
                ('expStartDate3', models.DateField(blank=True, null=True)),
                ('expEndDate3', models.DateField(blank=True, null=True)),
                ('hobbies1', models.CharField(blank=True, max_length=100, null=True)),
                ('hobbies2', models.CharField(blank=True, max_length=100, null=True)),
                ('hobbies3', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
