# Generated by Django 5.0.3 on 2024-06-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_resume_eduenddate1_alter_resume_eduenddate2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='Headline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='aboutYou',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='eduInstitute1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='eduTitle1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='expEndDate3',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experienceLevel',
            field=models.CharField(choices=[('one', 'ONE'), ('two', 'TWO'), ('three', 'THREE'), ('four', 'FOUR'), ('five', 'FIVE'), ('six', 'SIX'), ('seven', 'SEVEN'), ('eight', 'EIGHT'), ('nine', 'NINE'), ('ten', 'TEN'), ('internship', 'Internship'), ('fresh', 'Fresh')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
