# Generated by Django 5.0.3 on 2024-06-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_resume_headline_alter_resume_aboutyou_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='template_choice',
            field=models.CharField(default='template1', max_length=20),
        ),
    ]
