# Generated by Django 5.0.3 on 2024-06-23 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_resume_template_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='proEndDate1',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='proEndDate2',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='proEndDate3',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='proStartDate1',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='proStartDate2',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='proStartDate3',
        ),
    ]
