# Generated by Django 5.0.3 on 2024-06-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_resume_proenddate1_remove_resume_proenddate2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='expStartDate3',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='experienceCompany3',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='experienceTitle3',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='hobbies3',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='projectDescription3',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='projectTitle3',
        ),
        migrations.AlterField(
            model_name='resume',
            name='expEndDate3',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
