# Generated by Django 5.0.3 on 2024-06-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_resume_expstartdate3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='image',
        ),
    ]
