# Generated by Django 5.0.3 on 2024-06-23 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_resume_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='edu1Marks3',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='eduEndDate3',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='eduInstitute3',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='eduStartDate3',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='eduTitle3',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='hobbies1',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='hobbies2',
        ),
    ]
