# Generated by Django 5.0.3 on 2024-06-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_resume_edu1marks3_remove_resume_eduenddate3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='edu1Marks3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='eduEndDate3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='eduInstitute3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='eduStartDate3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='eduTitle3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
