# Generated by Django 5.0.3 on 2024-06-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_resume_eduenddate1_alter_resume_eduenddate2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='expEndDate3',
            new_name='expEndDate2',
        ),
    ]
